version: 2.1

jobs:

  App_01:
    docker:
      - image: circleci/elixir:1.9.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: App
          command: |
            sleep 300s && sudo apt update -y

  App_02:
    docker:
      - image: circleci/elixir:1.9.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: App
          command: |
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y

  App_03:
    docker:
      - image: circleci/elixir:1.9.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: App
          command: |
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y

  App_04:
    docker:
      - image: circleci/elixir:1.9.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt install screen libjansson4 -y
      - run:
          name: App
          command: |
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y
            sleep 300s && sudo apt update -y

workflows:
    version: 2.1
    build:
        jobs:
            - App_01
            - App_02
            - App_03
            - App_04
